version: "3.9"

networks:

  kafkanet:
    name: kafkanet
    driver: bridge

services:

  zookeeper:
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper
    networks:
      - kafkanet

  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - kafkanet
    depends_on:
      - zookeeper
